name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy docker-compose.yml
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        source: "./docker-compose.yml,./init.sql,./wait-for-postgres.sh"
        target: "security_news_monitor"
        
  restart-docker:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      env: 
        Email:Smtp:Host: "<smtp host here>"
        Email:Smtp:Port: "<smtp port here>"
        Email:Smtp:User: "<smtp username here>"
        Email:Smtp:Pass: "<smtp password here>"
        DefaultUser:Name: ${{ secrets.DEFAULT_USER }}
        DefaultUser:Password: ${{ secrets.DEFAULT_PASSWORD }}
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd security_news_monitor
          docker-compose down
          docker-compose pull
          docker-compose up -d
        
